language: android
android:
  components:
    - build-tools-23.0.0
    - extra-android-m2repository
    - android-23

jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a MAVEN_OPTS="-XX:MaxPermSize=2048M -Xmx4g -Xms2g"

script: ./gradlew clean build --stacktrace

